module.exports = [
fruits = [
	{id:1, name:'Darling Oranges', cost:20, src:'../public/img/myIMG/darlingFruits.jpg', popular:false},
	{id:2, name:'Strawberry', cost:25, src:'../public/img/myIMG/strawberry.jpg', popular:true},
	{id:3, name:'Soursoup', cost:16, src:'../public/img/myIMG/soursoup.jpg', popular:false},
	{id:4, name:'Nectarine', cost:12, src:'../public/img/myIMG/nectarine.jpg', popular:false},
	{id:5, name:'Cherry', cost:27, src:'../public/img/myIMG/cherry.jpg', popular:true},
	{id:6, name:'Pineapple', cost:30, src:'../public/img/myIMG/pineapple.jpg', popular:true},
	{id:7, name:'Banana', cost:25, src:'../public/img/myIMG/banana.jpg', popular:true},
	{id:8, name:'Chivi', cost:26, src:'../public/img/myIMG/chivi.jpg', popular:false},
	{id:9, name:'Apple', cost:20, src:'../public/img/myIMG/apple.jpg', popular:true},
	{id:10, name:'Grapes', cost:17, src:'../public/img/myIMG/grape.jpg', popular:true},
	{id:11, name:'Pear', cost:13, src:'../public/img/myIMG/pear.jpg', popular:false},
	{id:12, name:'Limone', cost:12, src:'../public/img/myIMG/limone.jpg', popular:false},
	{id:13, name:'Pomegranate', cost:21, src:'../public/img/myIMG/pomegranate.jpg', popular:false},
	{id:14, name:'Peach', cost:14, src:'../public/img/myIMG/peach.jpg', popular:false},
	{id:15, name:'Combat', cost:12, src:'../public/img/myIMG/combat.jpg', popular:false},
	{id:16, name:'Mandarine', cost:10, src:'../public/img/myIMG/mandarine.jpg', popular:false}
],
vegetables = [
	{id:1, name:'Melon', cost:22,src:'public/img/myIMG/melon.jpg', popular:true},
	{id:2, name:'WaterMelon', cost:19,src:'public/img/myIMG/watermelon.jpg', popular:true},
	{id:3, name:'Cabbage', cost:10,src:'public/img/myIMG/cabbage.jpg', popular:false},
	{id:4, name:'Cucumber', cost:8,src:'public/img/myIMG/cucumber.jpg', popular:false},
	{id:5, name:'Tomatoes', cost:12,src:'public/img/myIMG/tomatoes.jpg', popular:true},
	{id:6, name:'Carrot', cost:9,src:'public/img/myIMG/carrot.jpg', popular:false},
	{id:7, name:'Lichen Grass', cost:3,src:'public/img/myIMG/lichen.jpg', popular:false},
	{id:8, name:'Braccoli', cost:5,src:'public/img/myIMG/broccoli.jpg', popular:true},
	{id:9, name:'Potato', cost:6,src:'public/img/myIMG/potato.jpg', popular:false},
	{id:10, name:'Onion', cost:3,src:'public/img/myIMG/onion.jpg', popular:false},
	{id:11, name:'Pompkin', cost:5,src:'public/img/myIMG/pompkin.jpg', popular:false},
	{id:12, name:'Cauli Cabbage', cost:7,src:'public/img/myIMG/cauliCabbage.jpg', popular:false},
	{id:13, name:'Radish', cost:3,src:'public/img/myIMG/radish.jpg', popular:false},
	{id:14, name:'Mushroom', cost:1,src:'public/img/myIMG/mushroom.jpg', popular:false},
	{id:15, name:'Bean', cost:1,src:'public/img/myIMG/bean.jpg', popular:false},
	{id:16, name:'Bulgar', cost:6,src:'public/img/myIMG/bulgar.jpg', popular:false}
],
fastFoods = [
	{id:1, name:'Mr Burger', cost:23,src:'public/img/myIMG/mrBurger.jpg', popular:false},
	{id:2, name:'Sandwich', cost:33,src:'public/img/myIMG/sandwich.jpg', popular:true},
	{id:3, name:'Mittal', cost:40,src:'public/img/myIMG/mittal.jpg', popular:true},
	{id:4, name:'French Fries with Baskets', cost:22,src:'public/img/myIMG/frenchfries.jpg', popular:false},
	{id:5, name:'Singh Food', cost:45,src:'public/img/myIMG/singh.jpg', popular:false},
	{id:6, name:'Balaji', cost:50,src:'public/img/myIMG/balaji.jpg', popular:false},
	{id:7, name:'Scary', cost:37,src:'public/img/myIMG/scary.jpg', popular:false},
	{id:8, name:'Chipotle', cost:40,src:'public/img/myIMG/chipotle.jpg', popular:false},
	{id:9, name:'Italiano', cost:100,src:'public/img/myIMG/italiano.jpg', popular:true},
	{id:10, name:'Elbasan', cost:76,src:'public/img/myIMG/elbasan.jpg', popular:false},
	{id:11, name:'Japan Soura', cost:66,src:'public/img/myIMG/soura.jpg', popular:true},
	{id:12, name:'Noida', cost:70,src:'public/img/myIMG/noida.jpg', popular:true},
	{id:13, name:'Chatpat', cost:56,src:'public/img/myIMG/chatpat.jpg', popular:true},
	{id:14, name:'French Pizza', cost:89,src:'public/img/myIMG/frenchPizza.jpg', popular:true},
	{id:15, name:'Steiner', cost:38,src:'public/img/myIMG/steiner.jpg', popular:false},
	{id:16, name:'Lavache', cost:45,src:'public/img/myIMG/lavash.jpg', popular:true}
],
drinkes = [
	{id:1, name:'Ison Drink', cost:5,src:'public/img/myIMG/isoDrink.jpg', popular:false},
	{id:2, name:'Zazzle Drink', cost:3,src:'public/img/myIMG/zazzle.jpg', popular:false},
	{id:3, name:'Coca-cola', cost:6,src:'public/img/myIMG/cola.jpg', popular:true},
	{id:4, name:'Sweet Juice', cost:9,src:'public/img/myIMG/sweetSok.jpg', popular:true},
	{id:5, name:'Fanta', cost:6,src:'public/img/myIMG/fanta.jpg', popular:true},
	{id:6, name:'Citrus Juice', cost:7,src:'public/img/myIMG/citrus.jpg', popular:true},
	{id:7, name:'Watermelon Juice', cost:10,src:'public/img/myIMG/watermelonJuice.jpg', popular:true},
	{id:8, name:'Coctail for Summer', cost:12,src:'public/img/myIMG/coctail.jpg', popular:true},
]
]