module.exports = [
fruits = [
	{id:1, type:'fruit' , name:'Darling Oranges', cost:20, src:'../public/img/myIMG/darlingFruits.jpg', popular:false},
	{id:2, type:'fruit' , name:'Strawberry', cost:25, src:'../public/img/myIMG/strawberry.jpg', popular:true},
	{id:3, type:'fruit' , name:'Soursoup', cost:16, src:'../public/img/myIMG/soursoup.jpg', popular:false},
	{id:4, type:'fruit' , name:'Nectarine', cost:12, src:'../public/img/myIMG/nectarine.jpg', popular:false},
	{id:5, type:'fruit' , name:'Cherry', cost:27, src:'../public/img/myIMG/cherry.jpg', popular:true},
	{id:6, type:'fruit' , name:'Pineapple', cost:30, src:'../public/img/myIMG/pineapple.jpg', popular:true},
	{id:7, type:'fruit' , name:'Banana', cost:25, src:'../public/img/myIMG/banana.jpg', popular:true},
	{id:8, type:'fruit' , name:'Chivi', cost:26, src:'../public/img/myIMG/chivi.jpg', popular:false},
	{id:9, type:'fruit' , name:'Apple', cost:20, src:'../public/img/myIMG/apple.jpg', popular:true},
	{id:10, type:'fruit' , name:'Grapes', cost:17, src:'../public/img/myIMG/grape.jpg', popular:true},
	{id:11, type:'fruit' , name:'Pear', cost:13, src:'../public/img/myIMG/pear.jpg', popular:false},
	{id:12, type:'fruit' , name:'Limone', cost:12, src:'../public/img/myIMG/limone.jpg', popular:false},
	{id:13, type:'fruit' , name:'Pomegranate', cost:21, src:'../public/img/myIMG/pomegranate.jpg', popular:false},
	{id:14, type:'fruit' , name:'Peach', cost:14, src:'../public/img/myIMG/peach.jpg', popular:false},
	{id:15, type:'fruit' , name:'Combat', cost:12, src:'../public/img/myIMG/combat.jpg', popular:false},
	{id:16, type:'fruit' , name:'Mandarine', cost:10, src:'../public/img/myIMG/mandarine.jpg', popular:false}
],
vegetables = [
	{id:1, type:'vegetable' , name:'Melon', cost:22,src:'public/img/myIMG/melon.jpg', popular:true},
	{id:2, type:'vegetable' , name:'WaterMelon', cost:19,src:'public/img/myIMG/watermelon.jpg', popular:true},
	{id:3, type:'vegetable' , name:'Cabbage', cost:10,src:'public/img/myIMG/cabbage.jpg', popular:false},
	{id:4, type:'vegetable' , name:'Cucumber', cost:8,src:'public/img/myIMG/cucumber.jpg', popular:false},
	{id:5, type:'vegetable' , name:'Tomatoes', cost:12,src:'public/img/myIMG/tomatoes.jpg', popular:true},
	{id:6, type:'vegetable' , name:'Carrot', cost:9,src:'public/img/myIMG/carrot.jpg', popular:false},
	{id:7, type:'vegetable' , name:'Lichen Grass', cost:3,src:'public/img/myIMG/lichen.jpg', popular:false},
	{id:8, type:'vegetable' , name:'Braccoli', cost:5,src:'public/img/myIMG/broccoli.jpg', popular:true},
	{id:9, type:'vegetable' , name:'Potato', cost:6,src:'public/img/myIMG/potato.jpg', popular:false},
	{id:10, type:'vegetable' , name:'Onion', cost:3,src:'public/img/myIMG/onion.jpg', popular:false},
	{id:11, type:'vegetable' , name:'Pompkin', cost:5,src:'public/img/myIMG/pompkin.jpg', popular:false},
	{id:12, type:'vegetable' , name:'Cauli Cabbage', cost:7,src:'public/img/myIMG/cauliCabbage.jpg', popular:false},
	{id:13, type:'vegetable' , name:'Radish', cost:3,src:'public/img/myIMG/radish.jpg', popular:false},
	{id:14, type:'vegetable' , name:'Mushroom', cost:1,src:'public/img/myIMG/mushroom.jpg', popular:false},
	{id:15, type:'vegetable' , name:'Bean', cost:1,src:'public/img/myIMG/bean.jpg', popular:false},
	{id:16, type:'vegetable' , name:'Bulgar', cost:6,src:'public/img/myIMG/bulgar.jpg', popular:false}
],
fastFoods = [
	{id:1, type:'fastFood', name:'Mr Burger', cost:23,src:'public/img/myIMG/mrBurger.jpg', popular:false},
	{id:2, type:'fastFood', name:'Sandwich', cost:33,src:'public/img/myIMG/sandwich.jpg', popular:true},
	{id:3, type:'fastFood', name:'Mittal', cost:40,src:'public/img/myIMG/mittal.jpg', popular:true},
	{id:4, type:'fastFood', name:'French Fries with Baskets', cost:22,src:'public/img/myIMG/frenchfries.jpg', popular:false},
	{id:5, type:'fastFood', name:'Singh Food', cost:45,src:'public/img/myIMG/singh.jpg', popular:false},
	{id:6, type:'fastFood', name:'Balaji', cost:50,src:'public/img/myIMG/balaji.jpg', popular:false},
	{id:7, type:'fastFood', name:'Scary', cost:37,src:'public/img/myIMG/scary.jpg', popular:false},
	{id:8, type:'fastFood', name:'Chipotle', cost:40,src:'public/img/myIMG/chipotle.jpg', popular:false},
	{id:9, type:'fastFood', name:'Italiano', cost:100,src:'public/img/myIMG/italiano.jpg', popular:true},
	{id:10, type:'fastFood', name:'Elbasan', cost:76,src:'public/img/myIMG/elbasan.jpg', popular:false},
	{id:11, type:'fastFood', name:'Japan Soura', cost:66,src:'public/img/myIMG/soura.jpg', popular:true},
	{id:12, type:'fastFood', name:'Noida', cost:70,src:'public/img/myIMG/noida.jpg', popular:true},
	{id:13, type:'fastFood', name:'Chatpat', cost:56,src:'public/img/myIMG/chatpat.jpg', popular:true},
	{id:14, type:'fastFood', name:'French Pizza', cost:89,src:'public/img/myIMG/frenchPizza.jpg', popular:true},
	{id:15, type:'fastFood', name:'Steiner', cost:38,src:'public/img/myIMG/steiner.jpg', popular:false},
	{id:16, type:'fastFood', name:'Lavache', cost:45,src:'public/img/myIMG/lavash.jpg', popular:true}
],
drinkes = [
	{id:1, type:'drinkes',name:'Ison Drink', cost:5,src:'public/img/myIMG/isoDrink.jpg', popular:false},
	{id:2, type:'drinkes',name:'Zazzle Drink', cost:3,src:'public/img/myIMG/zazzle.jpg', popular:false},
	{id:3, type:'drinkes',name:'Coca-cola', cost:6,src:'public/img/myIMG/cola.jpg', popular:true},
	{id:4, type:'drinkes',name:'Sweet Juice', cost:9,src:'public/img/myIMG/sweetSok.jpg', popular:true},
	{id:5, type:'drinkes',name:'Fanta', cost:6,src:'public/img/myIMG/fanta.jpg', popular:true},
	{id:6, type:'drinkes',name:'Citrus Juice', cost:7,src:'public/img/myIMG/citrus.jpg', popular:true},
	{id:7, type:'drinkes',name:'Watermelon Juice', cost:10,src:'public/img/myIMG/watermelonJuice.jpg', popular:true},
	{id:8, type:'drinkes',name:'Coctail for Summer', cost:12,src:'public/img/myIMG/coctail.jpg', popular:true},
]
]